name: CI Expo Preview

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --ci --runInBand

  expo-preview:
    name: Expo preview build
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build Expo preview
        uses: expo/expo-github-action@v8
        with:
          eas-cache: true
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
          eas-version: latest
          eas-command: build --profile preview --platform all --non-interactive
