name: CI Expo Preview

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: cuidador-app/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: cuidador-app

      - name: Run tests
        run: npm test -- --ci --runInBand
        working-directory: cuidador-app

  expo-preview:
    name: Expo preview build
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: cuidador-app/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: cuidador-app

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-cache: true
          eas-cache: true
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build Expo preview
        run: npx eas build --profile preview --platform all --non-interactive
        working-directory: cuidador-app
